version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: docker-test-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: database-test-db
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin: 
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - default

  php:
    container_name: docker-test-php
    build:
      context: ./php
    volumes:
      - ./app:/var/www
    ports:
      - '9000:9000'
    depends_on:
      - db

  nginx:
    container_name: docker-test-nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db